server:
  port: 9999
  context-path: /uaa

security:
  user:
    name: user
    password: password

  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid





logging.level.org.springframework.security: DEBUG
